FROM python:3.10.11

ENV  SECRET_KEY afasfssegasgcgeges
ENV  DEBUG 0
ENV  DB_ENGINE django.db.backends.postgresql
ENV  DB_NAME default_name
ENV  DB_USER postgres
ENV  DB_PASSWORD postgres
ENV  DB_HOST postgredb

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN apt-get update && apt-get install -y libpq-dev
RUN pip install --no-cache-dir psycopg2

CMD python manage.py makemigrations && \
    python manage.py migrate && \
    python manage.py collectstatic && \
    gunicorn stocks_products.wsgi:application --bind 0.0.0.0:8000