name: тирп

on:
  push:
    branches:[main]

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DEBUG: "0"
      ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS }}
      DB_ENGINE: ${{ secrets.DB_ENGINE }}
      DB_NAME: ${{ secrets.DB_ENGINE }}
      DB_USER: ${{ secrets.DB_ENGINE }}
      DB_PASSWORD: ${{ secrets.DB_ENGINE }}
      DB_HOST: ${{ secrets.DB_ENGINE }}
      DB_PORT: ${{ secrets.DB_ENGINE }}

    steps:
      - name: Проверка репозитория на изменения
        uses: actions/checkout@v3

      - name: Установка python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
      
      - name: Установка зависимостей
        run: pip install -r requirements.txt

      - name: линтинг
        run: flake8 logistic/ stocks_products/ --exclude=logistic/migrations/

      - name: Тесты
        run: python manage.py test
        env:
          SECRET_KEY: ${{ env.SECRET_KEY }}
          DEBUG: ${{ env.DEBUG }}
          ALLOWED_HOSTS: ${{ env.ALLOWED_HOSTS }}
          DB_ENGINE: ${{ env.DB_ENGINE }}
          DB_NAME: ${{ env.DB_ENGINE }}
          DB_USER: ${{ env.DB_ENGINE }}
          DB_PASSWORD: ${{ env.DB_ENGINE }
          DB_HOST: ${{ env.DB_ENGINE }}
          DB_PORT: ${{ env.DB_ENGINE }}



